//
//  UIFont+YBKAdditions.swift
//
//  Generated by Zeplin on 5/23/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIFont {

    class func mrTextStyleFontHelvetica(fontSize: CGFloat) -> UIFont? {
        return UIFont(name: "Helvetica", size: fontSize)
    }

    class func mrTextStyleFontHelveticaBold(fontSize: CGFloat) -> UIFont? {
		return UIFont(name: "Helvetica-Bold", size: fontSize)
	}
    
    class func mrTextStyleFontPingFangTCMedium(fontSize: CGFloat) -> UIFont? {
        return UIFont(name: "PingFangTC-Medium", size: fontSize)
    }

    class func mrTextStyleFontSFUITextBold(fontSize: CGFloat) -> UIFont? {
        return systemFontOfSize(fontSize, weight: UIFontWeightBold)
    }
    
    class func mrTextStyleFontSFUITextMedium(fontSize: CGFloat) -> UIFont? {
        return systemFontOfSize(fontSize, weight: UIFontWeightMedium)
    }
    
    class func mrTextStyleFontSFUITextRegular(fontSize: CGFloat) -> UIFont? {
        return systemFontOfSize(fontSize, weight: UIFontWeightRegular)
    }

    class func mrTextStyleFontSFUITextSemibold(fontSize: CGFloat) -> UIFont? {
        return systemFontOfSize(fontSize, weight: UIFontWeightSemibold)
    }

}
