//
//  UIFont+YBKAdditions.swift
//
//  Generated by Zeplin on 5/23/16.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved. 
//

import UIKit

extension UIFont {

    class func mrTextStyleFontHelvetica(fontSize: CGFloat) -> UIFont? {
        return UIFont(name: "Helvetica", size: fontSize)
    }

    class func mrTextStyleFontHelveticaBold(fontSize: CGFloat) -> UIFont? {
		return UIFont(name: "Helvetica-Bold", size: fontSize)
	}
    
    class func mrTextStyleFontPingFangTCMedium(fontSize: CGFloat) -> UIFont? {
        return UIFont(name: "PingFangTC-Medium", size: fontSize)
    }
    
    // Roboto Mono
    class func mrTextStyleFontRobotoMonoBold(fontSize: CGFloat) -> UIFont? {
        return UIFont(name: "RobotoMono-Bold", size: fontSize)
    }
    
    class func mrTextStyleFontRobotoMonoBoldItalic(fontSize: CGFloat) -> UIFont? {
        return UIFont(name: "RobotoMono-BoldItalic", size: fontSize)
    }
    
    class func mrTextStyleFontRobotoMonoItalic(fontSize: CGFloat) -> UIFont? {
        return UIFont(name: "RobotoMono-Italic", size: fontSize)
    }
    
    class func mrTextStyleFontRobotoMonoLight(fontSize: CGFloat) -> UIFont? {
        return UIFont(name: "RobotoMono-Light", size: fontSize)
    }
    
    class func mrTextStyleFontRobotoMonoLightItalic(fontSize: CGFloat) -> UIFont? {
        return UIFont(name: "RobotoMono-LightItalic", size: fontSize)
    }

    class func mrTextStyleFontRobotoMonoMedium(fontSize: CGFloat) -> UIFont? {
        return UIFont(name: "RobotoMono-Medium", size: fontSize)
    }
    
    class func mrTextStyleFontRobotoMonoMediumItalic(fontSize: CGFloat) -> UIFont? {
        return UIFont(name: "RobotoMono-MediumItalic", size: fontSize)
    }
    
    class func mrTextStyleFontRobotoMonoRegular(fontSize: CGFloat) -> UIFont? {
        return UIFont(name: "RobotoMono-Regular", size: fontSize)
    }
    
    class func mrTextStyleFontRobotoMonoThin(fontSize: CGFloat) -> UIFont? {
        return UIFont(name: "RobotoMono-Thin", size: fontSize)
    }
    
    class func mrTextStyleFontRobotoMonoThinItalic(fontSize: CGFloat) -> UIFont? {
        return UIFont(name: "RobotoMono-ThinItalic", size: fontSize)
    }

    // System Font
    class func mrTextStyleFontSFUITextBold(fontSize: CGFloat) -> UIFont? {
        return systemFontOfSize(fontSize, weight: UIFontWeightBold)
    }
    
    class func mrTextStyleFontSFUITextMedium(fontSize: CGFloat) -> UIFont? {
        return systemFontOfSize(fontSize, weight: UIFontWeightMedium)
    }
    
    class func mrTextStyleFontSFUITextRegular(fontSize: CGFloat) -> UIFont? {
        return systemFontOfSize(fontSize, weight: UIFontWeightRegular)
    }

    class func mrTextStyleFontSFUITextSemibold(fontSize: CGFloat) -> UIFont? {
        return systemFontOfSize(fontSize, weight: UIFontWeightSemibold)
    }

}
